### ISSUE TITLE
インストール後に使用するとエラーが出て動作しなかった

### ISSUE THREAD

**Issue by takuhito-h** [msaktype/cheatah#6]
はじめまして、ブログで見かけて便利そうだと思い試用させていただきました。
が、スタイルガイドを生成しようとコマンドを打ってみましたら、エラーが出てしまいました。

以下にメッセージを記載しておきます。
ちなみにnodeのバージョンはv0.10.29です。

``` bash
$ cheatah -f trunk-ui-parts.css 

fs.js:432
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/usr/local/Cellar/node/0.10.29/lib/node_modules/cheatah/template/default.ejs'
    at Object.fs.openSync (fs.js:432:18)
    at Object.fs.readFileSync (fs.js:289:15)
    at Object.module.exports.importTemplate (/usr/local/lib/node_modules/cheatah/lib/util.js:8:28)
    at new Cheatah (/usr/local/lib/node_modules/cheatah/index.js:24:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/cheatah/bin/cheatah:37:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

ファイルが無いと言われているので、「/usr/local/Cellar/node/0.10.29/lib/」配下にnode_modulesディレクトリを作成し、そこにcheatahを入れたら無事動作しました。

homebrewでnodeを動かしているのが悪かったんでしょうか。
自己解決したので良かったんですが、一応ご報告まで。

**Comment by msaktype** [comment]
返信が遅れて申し訳ございません。

報告ありがとうございました！
このリポジトリは完全に放置してしまっていたので、これから積極的にメンテナンスしていければと思っています。
